import type { Metadata } from 'next';
import './globals.css';
import { robotoCondensed, roboto } from './fonts';
import Header from '@/app/components/Header';
import Footer from '@/app/components/Footer';
import { ReduxProviders } from '@/app/redux/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className={`${robotoCondensed.variable} ${roboto.variable}`}>
      <body>
      <Header />
      <ReduxProviders>
        {children}
      </ReduxProviders>
      <Footer />
      </body>
    </html>
  );
}
