import type { Metadata } from 'next';
import './globals.css';
import { robotoCondensed } from './fonts';
import Header from '@/app/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" className={robotoCondensed.variable}>
      <body>
      <Header />
      {children}
      </body>
    </html>
  );
}
